#Created on Sun Feb 23 03:43:07 2025
#@author: aadi
# revobots.yaml

# Whether to use the Revobot (socket-based) arms for leader, follower, or both.
# If false, we use normal Dynamixel arms for Koch.
use_revobot_leader: False
use_revobot_follower: True
# skip_frame: 15
# start_end_speed: 0
# angular_speed: 0

_target_: lerobot.common.robot_devices.robots.revobots_manipulator.RevobotsManipulatorRobot


# Normal Koch config
robot_type: koch
calibration_dir: .cache/calibration/koch

max_relative_target: null

leader_arms:
  main:
    _target_: lerobot.common.robot_devices.motors.dynamixel.DynamixelMotorsBus
    port: /dev/ttyACM1
    motors:
      # name: (index, model)
      shoulder_pan: [1, "xl330-m077"]
      shoulder_lift: [2, "xl330-m077"]
      elbow_flex: [3, "xl330-m077"]
      wrist_flex: [4, "xl330-m077"]
      wrist_roll: [5, "xl330-m077"]
      gripper: [6, "xl330-m077"]

follower_arms:
  main:
    _target_: lerobot.common.robot_devices.motors.dynamixel.DynamixelMotorsBus
    port: /dev/ttyACM0
    motors:
      # name: (index, model)
      shoulder_pan: [1, "xl430-w250"]
      shoulder_lift: [2, "xl430-w250"]
      elbow_flex: [3, "xl330-m288"]
      wrist_flex: [4, "xl330-m288"]
      wrist_roll: [5, "xl330-m288"]
      gripper: [6, "xl330-m288"]

cameras:
  phone:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 6 # Phone (Top View) Camera
    fps: 30
    width: 640
    height: 480
  laptop:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 8 # Laptop Camera (Front View)
    fps: 30
    width: 640
    height: 480
  wrist_1:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 12 #Gripper Tilted Camera
    fps: 15
    width: 640
    height: 480
  wrist_2:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 16 #Micro-scope camera
    fps: 30
    width: 640
    height: 480


# Socket config for Revobot if we want to use it. 
# We just keep it here so we can set IP/port for either leader or follower.
# Revobot arms definitions (socket details are embedded within the arm definitions)
revobot_leader_arms:
  main:
    _target_: lerobot.common.robot_devices.motors.revomotors.RevobotRobotBus
    socket_ip: "127.0.0.1"
    socket_port: 5050
    motors:
      shoulder_pan: [1, "a"]
      shoulder_lift: [2, "a"]
      elbow_flex: [3, "a"]
      wrist_flex: [4, "a"]
      wrist_roll: [5, "a"]
      gripper: [6, "a"]


revobot_follower_arms:
  main:
    _target_: lerobot.common.robot_devices.motors.revomotors.RevobotRobotBus
    socket_ip: "192.168.0.142"
    #socket_ip: "97.188.81.36"
    socket_port: 50000
    motors:
      shoulder_pan: [1, "a"]
      shoulder_lift: [2, "a"]
      elbow_flex: [3, "a"]
      wrist_flex: [4, "a"]
      wrist_roll: [5, "a"]
      gripper: [6, "a"]
      

gripper_open_degree: 35.156
